### ISSUE TITLE
Building an AHRS 9DOF RAZOR tuto error #YPR=0.00,0.00,0.00 NEED HELP!!!

### ISSUE THREAD

**Issue by zelda23** [Razor-AHRS/razor-9dof-ahrs#42]
thank you GITHUB

**Comment by mlvo83** [comment]
having the same issue. Did you ever get this working?

**Comment by zelda23** [comment]
hello no it didn't work. I used an another AHRS of adafruit with arduino UNO.
it worked good and it was chaep.
----Message d'origine----
De : notifications@github.com
Date : 26/11/2016 - 04:02 (GMT)
À : razor-9dof-ahrs@noreply.github.com
Cc : 2nm@bluewin.ch, author@noreply.github.com
Objet : Re: [Razor-AHRS/razor-9dof-ahrs] Building an AHRS 9DOF RAZOR tuto error #YPR=0.00,0.00,0.00 NEED HELP!!! (#42)
having the same issue. Did you ever get this working?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Razor-AHRS/razor-9dof-ahrs","title":"Razor-AHRS/razor-9dof-ahrs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Razor-AHRS/razor-9dof-ahrs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mlvo83 in #42: having the same issue. Did you ever get this working?\r\n"}],"action":{"name":"View Issue","url":"https://github.com/Razor-AHRS/razor-9dof-ahrs/issues/42#issuecomment-263040851"}}}

**Comment by mlvo83** [comment]
Thanks for replying. Would you be willing to share the name of the one you used.  I have been looking at some of the adafruit sensors but I'm now getting gun shy

**Comment by zelda23** [comment]
hi: "
Adafruit 10-DOF IMU Breakout - L3GD20H + LSM303 + BMP180"
https://www.adafruit.com/products/1604
----Message d'origine----
De : notifications@github.com
Date : 27/11/2016 - 03:35 (GMT)
À : razor-9dof-ahrs@noreply.github.com
Cc : 2nm@bluewin.ch, author@noreply.github.com
Objet : Re: [Razor-AHRS/razor-9dof-ahrs] Building an AHRS 9DOF RAZOR tuto error #YPR=0.00,0.00,0.00 NEED HELP!!! (#42)
Thanks for replying. Would you be willing to share the name of the one you used.  I have been looking at some of the adafruit sensors but I'm now getting gun shy
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
  
  
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Razor-AHRS/razor-9dof-ahrs","title":"Razor-AHRS/razor-9dof-ahrs","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Razor-AHRS/razor-9dof-ahrs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@mlvo83 in #42: Thanks for replying. Would you be willing to share the name of the one you used.  I have been looking at some of the adafruit sensors but I'm now getting gun shy"}],"action":{"name":"View Issue","url":"https://github.com/Razor-AHRS/razor-9dof-ahrs/issues/42#issuecomment-263098560"}}}

**Comment by zelda23** [comment]
Thank you github
